### ISSUE TITLE
ingredient/meal page

### ISSUE THREAD

**Issue by ewelinasobora** [4codeCrushers/mealMaster#5]
- [ ] - Display ingredient/meal information: fat, carbo, calories etc. , (recipe ? )
- [ ] - API call to image api
- [ ] - Display image on page
- [ ] - Make sure ingredient/ meal list is displayed in calendar

**Comment by ph8tfunk** [comment]
User Story:

 - as a User I should be able to select/display a meal for a particular day
 - the meal should show ingredients
 - the meal should show a picture of the meal
 - the meal should show nutritional information
